// ============================================================
// API Endpoints for AssetFlow
// ============================================================

export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/register',
    LOGOUT: '/api/auth/logout',
    REFRESH: '/api/auth/refresh',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    VERIFY_EMAIL: '/api/auth/verify-email',
    PROFILE: '/api/auth/profile',
  },
  DASHBOARD: {
    STATS: '/api/dashboard/stats',
    TRENDS: '/api/dashboard/trends',
    ACTIVITIES: '/api/dashboard/activities',
    KPIS: '/api/dashboard/kpis',
  },
  DEPARTMENTS: {
    LIST: '/api/departments',
    DETAILS: (id: string) => `/api/departments/${id}`,
    CREATE: '/api/departments',
    UPDATE: (id: string) => `/api/departments/${id}`,
    DELETE: (id: string) => `/api/departments/${id}`,
    HIERARCHY: '/api/departments/hierarchy',
    STATS: (id: string) => `/api/departments/${id}/stats`,
  },
  EMPLOYEES: {
    LIST: '/api/employees',
    DETAILS: (id: string) => `/api/employees/${id}`,
    CREATE: '/api/employees',
    UPDATE: (id: string) => `/api/employees/${id}`,
    DELETE: (id: string) => `/api/employees/${id}`,
    ASSETS: (id: string) => `/api/employees/${id}/assets`,
    ACTIVITY: (id: string) => `/api/employees/${id}/activity`,
  },
  ASSETS: {
    LIST: '/api/assets',
    DETAILS: (id: string) => `/api/assets/${id}`,
    CREATE: '/api/assets',
    UPDATE: (id: string) => `/api/assets/${id}`,
    DELETE: (id: string) => `/api/assets/${id}`,
    QR: (id: string) => `/api/assets/${id}/qr`,
    GALLERY: (id: string) => `/api/assets/${id}/gallery`,
    DOCUMENTS: (id: string) => `/api/assets/${id}/documents`,
    HISTORY: (id: string) => `/api/assets/${id}/history`,
    TIMELINE: (id: string) => `/api/assets/${id}/timeline`,
    CATEGORIES: '/api/assets/categories',
    STATS: '/api/assets/stats',
    BULK_CREATE: '/api/assets/bulk',
    EXPORT: '/api/assets/export',
    IMPORT: '/api/assets/import',
  },
  ALLOCATIONS: {
    LIST: '/api/allocations',
    DETAILS: (id: string) => `/api/allocations/${id}`,
    CREATE: '/api/allocations',
    RETURN: (id: string) => `/api/allocations/${id}/return`,
    ACTIVE: '/api/allocations/active',
    HISTORY: '/api/allocations/history',
    OVERDUE: '/api/allocations/overdue',
  },
  TRANSFERS: {
    LIST: '/api/transfers',
    DETAILS: (id: string) => `/api/transfers/${id}`,
    CREATE: '/api/transfers',
    APPROVE: (id: string) => `/api/transfers/${id}/approve`,
    REJECT: (id: string) => `/api/transfers/${id}/reject`,
    COMPLETE: (id: string) => `/api/transfers/${id}/complete`,
    CANCEL: (id: string) => `/api/transfers/${id}/cancel`,
    PENDING: '/api/transfers/pending',
  },
  BOOKINGS: {
    LIST: '/api/bookings',
    DETAILS: (id: string) => `/api/bookings/${id}`,
    CREATE: '/api/bookings',
    APPROVE: (id: string) => `/api/bookings/${id}/approve`,
    REJECT: (id: string) => `/api/bookings/${id}/reject`,
    CANCEL: (id: string) => `/api/bookings/${id}/cancel`,
    CALENDAR: '/api/bookings/calendar',
    CHECK_CONFLICT: '/api/bookings/check-conflict',
    TODAY: '/api/bookings/today',
    UPCOMING: '/api/bookings/upcoming',
  },
  MAINTENANCE: {
    LIST: '/api/maintenance',
    DETAILS: (id: string) => `/api/maintenance/${id}`,
    CREATE: '/api/maintenance',
    APPROVE: (id: string) => `/api/maintenance/${id}/approve`,
    ASSIGN: (id: string) => `/api/maintenance/${id}/assign`,
    START: (id: string) => `/api/maintenance/${id}/start`,
    COMPLETE: (id: string) => `/api/maintenance/${id}/complete`,
    CLOSE: (id: string) => `/api/maintenance/${id}/close`,
    PENDING: '/api/maintenance/pending',
    HISTORY: '/api/maintenance/history',
    STATS: '/api/maintenance/stats',
  },
  AUDIT: {
    CYCLES: '/api/audit/cycles',
    CYCLE_DETAILS: (id: string) => `/api/audit/cycles/${id}`,
    CREATE_CYCLE: '/api/audit/cycles',
    UPDATE_CYCLE: (id: string) => `/api/audit/cycles/${id}`,
    CLOSE_CYCLE: (id: string) => `/api/audit/cycles/${id}/close`,
    RESULTS: (cycleId: string) => `/api/audit/cycles/${cycleId}/results`,
    VERIFY: (cycleId: string) => `/api/audit/cycles/${cycleId}/verify`,
    DISCREPANCY: (cycleId: string) => `/api/audit/cycles/${cycleId}/discrepancy`,
    STATS: '/api/audit/stats',
  },
  NOTIFICATIONS: {
    LIST: '/api/notifications',
    MARK_READ: (id: string) => `/api/notifications/${id}/read`,
    MARK_ALL_READ: '/api/notifications/mark-all-read',
    ARCHIVE: (id: string) => `/api/notifications/${id}/archive`,
    DELETE: (id: string) => `/api/notifications/${id}`,
    UNREAD_COUNT: '/api/notifications/unread-count',
    SETTINGS: '/api/notifications/settings',
  },
  REPORTS: {
    LIST: '/api/reports',
    GENERATE: '/api/reports/generate',
    DOWNLOAD: (id: string) => `/api/reports/${id}/download`,
    DELETE: (id: string) => `/api/reports/${id}`,
    TEMPLATES: '/api/reports/templates',
    SCHEDULE: '/api/reports/schedule',
  },
  ACTIVITY_LOGS: {
    LIST: '/api/activity-logs',
    EXPORT: '/api/activity-logs/export',
    STATS: '/api/activity-logs/stats',
  },
  SETTINGS: {
    GENERAL: '/api/settings/general',
    SECURITY: '/api/settings/security',
    NOTIFICATIONS: '/api/settings/notifications',
    INTEGRATIONS: '/api/settings/integrations',
    THEME: '/api/settings/theme',
    BACKUP: '/api/settings/backup',
    LOGS: '/api/settings/logs',
  },
  PROFILE: {
    GET: '/api/profile',
    UPDATE: '/api/profile',
    CHANGE_PASSWORD: '/api/profile/change-password',
    AVATAR: '/api/profile/avatar',
    PREFERENCES: '/api/profile/preferences',
  },
  HELP: {
    ARTICLES: '/api/help/articles',
    ARTICLE: (id: string) => `/api/help/articles/${id}`,
    SEARCH: '/api/help/search',
    CONTACT: '/api/help/contact',
    FEEDBACK: '/api/help/feedback',
    FAQ: '/api/help/faq',
  },
  SEARCH: {
    GLOBAL: '/api/search',
    RECENT: '/api/search/recent',
    SUGGESTIONS: '/api/search/suggestions',
  },
} as const;